### ISSUE TITLE
Feature Request - Omitting Feature Hub API Key Logging

### ISSUE THREAD

**Issue by jkim007** [featurehub-io/featurehub-ruby-sdk#29]
**Is your feature request related to a problem? Please describe.**
As a Feature Hub consumer, from a (security standpoint) seeing the API key consistently logged raises security concerns.

**Describe the solution you'd like**
It would be nice to be able to disable API key logging either via an environment variable or flag in the Feature Hub UI.

**Describe alternatives you've considered**
Creating a custom logging wrapper that extrapolates relevant information and removes the API key from all transmitted logs.

**Additional context**

**Comment by rvowles** [comment]
Hi Jim!

We're happy to remove them from info level logs, but we will be leaving them in debug and tracing logs. Those are critical for SRE level diagnostics. Are you seeing them in INFO level in any particular location?

**Comment by jkim007** [comment]
@rvowles 

In FeatureHub's source code, they emit the api key in logs here: [https://github.com/featurehub-io/featurehub-ruby-sdk/blob/1ad6e256078c9aaeef3d178d[…]ff/featurehub-sdk/lib/feature_hub/sdk/streaming_edge_service.rb](https://github.com/featurehub-io/featurehub-ruby-sdk/blob/1ad6e256078c9aaeef3d178ddc256499e95e9dff/featurehub-sdk/lib/feature_hub/sdk/streaming_edge_service.rb#L61) and here: [https://github.com/featurehub-io/featurehub-ruby-sdk/blob/1ad6e256078c9aaeef3d178d[…]95e9dff/featurehub-sdk/lib/feature_hub/sdk/poll_edge_service.rb](https://github.com/featurehub-io/featurehub-ruby-sdk/blob/1ad6e256078c9aaeef3d178ddc256499e95e9dff/featurehub-sdk/lib/feature_hub/sdk/poll_edge_service.rb#L115) (because they use the API key as a path parameter instead of, say, a header on the request)

The field is exposed on failed requests as connect.rest.method, which puts the url in its message e.g. responded: GET - `http://<featurehub-host>/features/default/<api-key>`

**Comment by rvowles** [comment]
Hey @jkim007 - I've moved this to the Ruby SDK, and absolutely, no problem :-)

**Comment by rvowles** [comment]
@jkim007 which version of Ruby are you folks on? I am only testing this on 3.0.6+ at the moment

**Comment by rvowles** [comment]
Also you may wish to check if the attached PR matches your expectations?

**Comment by jkim007** [comment]
@rvowles Hello, the PR you posted only changes the info logs to debug logs. This doesn't remove the issue where the API key is still being emitted.

Also, we are on Ruby 3.1

**Comment by rvowles** [comment]
I'm a little confused, I would expect you to just not set the log level for the sdk to debug unless you want to debug what the sdk is doing?

**Comment by jkim007** [comment]
Apologies, I got confused. You're completely right. If the debug logs are being emitted then that's something I should fix on my end.

Thank you!!

**Comment by rvowles** [comment]
1.2.2 has been released!
