### ISSUE TITLE
Syncing feature state upstream

### ISSUE THREAD

**Issue by kasperite** [featurehub-io/featurehub-ruby-sdk#34]
Hi @rvowles 👋  

Existing README is sparse so I guess I will double check here. How do you update feature flag using this SDK? I can update feature state using `FeatureHubRepository#notify` but can't see how the state is synced upstream to FeatureHub. 

Am I right to think that current SDK doesn't have this ability?

Thanks

**Comment by rvowles** [comment]
Heya - the SDK is primarily for use in evaluating features. There is a Test API that lets you update  features (but only their default value) and only when you have given  it permission to do  so. Its intended to allow you change  the default value  when doing automated tests. 

We don't have  an ADK for Ruby,  but its just code generated  from the OpenAPI docs if you want to have an app do anything  with the  backend, you can do pretty much anything.

**Comment by kasperite** [comment]
Sweet! thanks for confirming that 👍
