### ISSUE TITLE
Clarification of 236 response

### ISSUE THREAD

**Issue by kasperite** [featurehub-io/featurehub-ruby-sdk#35]
Hi @rvowles 

I think this question is unrelated to how SDK implemented but worth checking.

When implementing polling, I notice response status is always 236 which implies stale environment as documented in https://docs.featurehub.io/featurehub/latest/sdks-development.html. The polling task get cancelled as the result. I tried to `poll` again few times eg `config.new_context.build.feature("FLAG")` but it still returns 236 regardless.

Any ideas why?

Thanks

**Comment by rvowles** [comment]
Only SaaS should send this result, and only when you exceed your specified usage limit (its in the system config), are you using Saas?

**Comment by kasperite** [comment]
Ah! Gotcha. Yes I am using Saas version. So I just need to update threshold number in billing page then :). I guess the total API requests will be reset at the end of billing cycle?

**Comment by rvowles** [comment]
Yep - thats exactly right. You can set the limit to zero which is unlimited if you like.

**Comment by kasperite** [comment]
Awesome, thanks for your super quick response 💯
